### ISSUE TITLE
Chart not running on my environment

### ISSUE THREAD

**Issue by ppiotrow** [feast-dev/feast-helm-charts#2]
```
➜  export HELM_DEBUG=1
➜  helm install feast-release feast-charts/feast
install.go:173: [debug] Original chart version: ""
Error: scheme "gs" not supported
helm.go:81: [debug] scheme "gs" not supported
helm.sh/helm/v3/pkg/getter.Providers.ByScheme
	/private/tmp/helm-20210204-99981-1f8vc0y/pkg/getter/getter.go:156
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/private/tmp/helm-20210204-99981-1f8vc0y/pkg/downloader/chart_downloader.go:94
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/private/tmp/helm-20210204-99981-1f8vc0y/pkg/action/install.go:675
```	

```
➜   helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
I'm able to deploy other helm charts like bitmami/redis.

**Comment by woop** [comment]
Thanks for raising this issue @ppiotrow. Others have also noted this problem, specifically @beatgeek. I think it may be a problem with Helm 2 vs Helm 3.

**Comment by beatgeek** [comment]
Correct I experienced the same error. Re-ran the update later and was able to deploy it. I think the issue is the use of version 2.2 of their script.

I can't explain why it didn't work and then later worked.

**Comment by kuromt** [comment]
I am facing same trouble.

```
Error: scheme "gs" not supported
```

I add helm-gcs plugin accordint to the code.
https://github.com/feast-dev/feast-helm-charts/blob/main/scripts/push-helm-charts.sh#L13

After that, I was requestes google credential.
```
panic: new client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

So I assume that the bucket gs://feast-helm-charts was made private last night.

**Comment by woop** [comment]
@ppiotrow and @kuromt I just ran the following command which uses a publicly available helm docker image to generate the Feast Kubernetes objects. It seems to work

```
docker run devth/helm bash -c "helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com && helm repo update && helm template feast-release feast-charts/feast"
```

Can you confirm that the above command works for you? If so, can you try and delete and re-add the Feast Helm repo? Also, please confirm that you are using the right helm repo path.

**Comment by ppiotrow** [comment]
The above command works for me.

**Comment by woop** [comment]
@ppiotrow I'd love to help you but I dont know how to recreate the problem. Do you know what steps I can follow to recreate it?

**Comment by kuromt** [comment]
@woop Thanks, the command works fine too.

Helm version  in my environemnt

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

and in devth/helm, 

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Above shows both of uses same helm version, but I find that kubectl and gcloud command that are installed in devth/helm image are not installed in my container image(centos7).

However, after install gcloud-sdk and kubectl, error was not change.

**Comment by woop** [comment]
@kuromt do you know the steps that I can follow to reproduce the problem?

**Comment by kuromt** [comment]
@woop Yes. I run the following command.

```
$ docker run -it --rm centos:7 bash
[root@bf21c442322c /]# curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | VERIFY_CHECKSUM=false bash
[root@bf21c442322c /]# helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
"feast-charts" has been added to your repositories
[root@bf21c442322c /]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "feast-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
[root@bf21c442322c /]# HELM_DEBUG=1  helm template feast-release feast-charts/feast
install.go:173: [debug] Original chart version: ""
Error: scheme "gs" not supported
helm.go:81: [debug] scheme "gs" not supported
helm.sh/helm/v3/pkg/getter.Providers.ByScheme
	/home/circleci/helm.sh/helm/pkg/getter/getter.go:156
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:94
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/home/circleci/helm.sh/helm/pkg/action/install.go:675
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:185
main.newTemplateCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

**Comment by woop** [comment]
> @woop Yes. I run the following command.
> 
> ```
> $ docker run -it --rm centos:7 bash
> [root@bf21c442322c /]# curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | VERIFY_CHECKSUM=false bash
> [root@bf21c442322c /]# helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
> "feast-charts" has been added to your repositories
> [root@bf21c442322c /]# helm repo update
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "feast-charts" chart repository
> Update Complete. ⎈Happy Helming!⎈
> [root@bf21c442322c /]# HELM_DEBUG=1  helm template feast-release feast-charts/feast
> install.go:173: [debug] Original chart version: ""
> Error: scheme "gs" not supported
> helm.go:81: [debug] scheme "gs" not supported
> helm.sh/helm/v3/pkg/getter.Providers.ByScheme
> 	/home/circleci/helm.sh/helm/pkg/getter/getter.go:156
> helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
> 	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:94
> helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
> 	/home/circleci/helm.sh/helm/pkg/action/install.go:675
> main.runInstall
> 	/home/circleci/helm.sh/helm/cmd/helm/install.go:185
> main.newTemplateCmd.func2
> 	/home/circleci/helm.sh/helm/cmd/helm/template.go:73
> github.com/spf13/cobra.(*Command).execute
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
> github.com/spf13/cobra.(*Command).ExecuteC
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
> github.com/spf13/cobra.(*Command).Execute
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
> main.main
> 	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:204
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1374
> ```

Great, I am able to reproduce the problem locally. I'll spend some time to see if I can find the root cause.

**Comment by paravatha** [comment]
Same issue, this never works..I tried several times

```
helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
helm repo update
```

also, maybe minor detail, why do you need to mention "helm". It seems like redundant 
https://feast-**helm**-charts.storage.googleapis.com

**Comment by woop** [comment]
Should work now. [Helm GCS](https://github.com/hayorov/helm-gcs) was converting the index.yaml URLs to gs paths. Please confirm @paravatha @kuromt @ppiotrow

**Comment by ppiotrow** [comment]
Works now, thanks for quick fix.

**Comment by woop** [comment]
> also, maybe minor detail, why do you need to mention "helm"?. It seems like redundant
feast-helm-charts

I guess it's redundant if you already know what a Helm chart is, and I'd rather make it explicit.

**Comment by woop** [comment]
I've closed this issue for now after multiple confirmations (here and Slack). Please let me know if you are still running into problems.

**Comment by paravatha** [comment]
> I guess it's redundant if you already know what a Helm chart is, and I'd rather make it explicit.

Makes sense, thanks @woop
