### ISSUE TITLE
Missing prometheus and grafana in charts

### ISSUE THREAD

**Issue by paravatha** [feast-dev/feast-helm-charts#3]
https://github.com/feast-dev/feast-helm-charts#feast-helm-charts

The optional charts for prometheus, grafana etc are not available

**Comment by woop** [comment]
Good catch @paravatha, will update the documentation. We've intentionally removed those since most teams install those components separately and they aren't configured in any special way for Feast.

**Comment by paravatha** [comment]
Thanks @woop
Have you thought of still keeping them, but make them optional with default as false?

**Comment by paravatha** [comment]
I found them very useful to quickly check number of features, latency etc.

**Comment by woop** [comment]
Hey @paravatha. I'm not seeing a super strong reason for it to be bundled into our chart right now. Any reason they can't be installed separately?

**Comment by paravatha** [comment]
No worries. I cloned the 0.9 branch. I will manually install them
