### ISSUE TITLE
Problem in feast-jupyter chart templates

### ISSUE THREAD

**Issue by josegpg** [feast-dev/feast-helm-charts#4]
Hello!

I'm following the docs for deploying feast on GCP and I noticed you moved the charts from the feast repo to this one. When applying the changes to the Terraform files I'm getting the following error:

`Error: template: feast/charts/feast-jupyter/templates/deployment.yaml:32:30: executing "feast/charts/feast-jupyter/templates/deployment.yaml" at <{{template "chart.fullname" .}}>: template "chart.fullname" not defined`

I think the problem might be [here](https://github.com/feast-dev/feast-helm-charts/blob/main/charts/feast-jupyter/templates/deployment.yaml#L32), probably it should be `feast-jupyter.fullname` instead of `chart.fullname` however I'm not sure.

Let me know if there's an issue or maybe I'm doing something wrong.

Regards

**Comment by woop** [comment]
@josegpg which chart repository are you using?

**Comment by josegpg** [comment]
The one in the Readme:
`feast-charts https://feast-helm-charts.storage.googleapis.com`

**Comment by woop** [comment]
Thanks for raising. I've not had time to look at this issue, but I think we need to retest the Terraform installations now that the repo has been refactored.

**Comment by josegpg** [comment]
Hi @woop!

Here's some update.
I cloned this repo and did the change I mentioned above and it worked. I got the feast-jupyter pod running! (I'm still having some other issues to get the GCP K8s guide working but this is a good step)

I created [this](https://github.com/feast-dev/feast-helm-charts/pull/5) PR in case it's useful for you.

Regards

**Comment by woop** [comment]
Thanks @josegpg! Merged. Will release a new version.
